// Generated by CoffeeScript 1.6.3
(function() {
  $('#user_not_logged_in').hide();

  $('#user_name').attr('href', '/?42757');

  $('#user_name').html('zh99998');

  $('#user_logged_in').show();

}).call(this);

/*
//@ sourceMappingURL=application.map
*/
