// Generated by CoffeeScript 1.6.3
(function() {
  var search_result_games_template;

  search_result_games_template = Mustache.compile($('#search_result_games_template').html());

  $.getJSON('http://3.chengguangtest.sinaapp.com/test/games', function(data) {
    data.score = function() {
      var score, score_count;
      if (score_count = parseInt(this.score1) + parseInt(this.score2) + parseInt(this.score3) + parseInt(this.score4) + parseInt(this.score5)) {
        score = (parseInt(this.score1) + parseInt(this.score2) * 2 + parseInt(this.score3) * 3 + parseInt(this.score4) * 4 + parseInt(this.score5) * 5) / score_count;
        console.log(score_count);
        return Array(score + 1).join('★') + Array(5 - score + 1).join('☆');
      } else {
        return '没有评分';
      }
    };
    return $('#search_result').html(search_result_games_template(data));
  }).error(function(xhr) {
    return $('#search_result').html(xhr.responseText);
  });

}).call(this);

/*
//@ sourceMappingURL=search.map
*/
